export const CONFIG = {
  peopleDir: './data/people',
  peopleManifestPath: './data/people/index.json',
  personFileExtension: '.yaml',
};

export const FIELD_LABELS = {
  id: 'ID',
  birth_name: 'Имя при рождении',
  name_changes: 'Изменения имени',
  sex: 'Пол',
  birth: 'Рождение',
  death: 'Смерть',
  parents: 'Родители',
  siblings: 'Братья и сёстры',
  spouses: 'Супруги',
  children: 'Дети',
  education: 'Образование',
  class_title: 'Сословие / социальный статус',
  religion: 'Вероисповедание',
  nationality: 'Национальность',
  profession: 'Профессии',
  job_places: 'Работа',
  military: 'Военная служба',
  residences: 'Места проживания',
  hobbies: 'Хобби и интересы',
  character: 'Характер',
  appearance: 'Внешность',
  health: 'Здоровье',
  other_info: 'Дополнительная информация',
  sources: 'Источники',
  media: 'Медиа',
};

export const SECTION_ORDER = [
  'birth_name',
  'name_changes',
  'birth',
  'death',
  'parents',
  'siblings',
  'spouses',
  'children',
  'education',
  'class_title',
  'religion',
  'nationality',
  'profession',
  'job_places',
  'military',
  'residences',
  'hobbies',
  'character',
  'appearance',
  'health',
  'other_info',
  'sources',
  'media',
];
