# Идентификатор личности в базе данных
id:

birth_name:
  surname:
  first_name:
  patronymic:

# Другие имена, которые человек использовал в течение жизни
name_changes:
  - name:
    date:
      day:
      month:
      year:
    reason: (брак, развод, смена имени)

sex: (м, ж, другой)

birth:
  date:
    day:
    month:
    year:
  date_raw: (например, конец 1920-х годов)
  place:

# Если человек ещё жив, нажмите "Ещё жив(-а)" в правом верхнем углу
death:
  date:
    day:
    month:
    year:
  date_raw: (например, конец 1920-х годов)
  place:
  cause:
  burial_place:

# Биологические, приемные, сводные
parents:
  - person_id:
    relation_type: (мать, отец, мачеха, отчим, приемный отец, приемная мать)

siblings:
  - person_id:
    relation_type: (биологический, приемный, сводный по отцу, сводный по матери)

spouses:
  - person_id:
    marriage:
      - date:
          day:
          month:
          year:
        place:
    divorce:
      - date:
          day:
          month:
          year:
        other:

children:
  - person_id:
    relation_type: (биологический, приемный, сводный)

education:
  - education_info:

class_title:
religion:
nationality:

jobs:
  - job:

military_service:
  - service_info:

war_participation:
  - war:

achievements:
  - achievement:

residences:
  - residence_info:

hobbies:
character:
appearance:
health:

# Дополнительная информация с произвольными подпунктами.
other_info:
  - label:
    text:

sources:
  - source:

media:
  - description:
    link:
