export const PERSON_FIELD_LABELS = {
  id: 'ID',
  birth_name: 'Имя при рождении',
  name_changes: 'Изменения имени',
  sex: 'Пол',
  birth: 'Рождение',
  death: 'Смерть',
  parents: 'Родители',
  siblings: 'Братья и сёстры',
  spouses: 'Супруги',
  children: 'Дети',
  education: 'Образование',
  class_title: 'Сословие / социальный статус',
  religion: 'Вероисповедание',
  nationality: 'Национальность',
  jobs: 'Работа',
  military_service: 'Военная служба',
  war_participation: 'Участие в конфликтах и военные годы',
  achievements: 'Достижения и награды',
  residences: 'Места проживания',
  hobbies: 'Хобби и интересы',
  character: 'Характер',
  appearance: 'Внешность',
  health: 'Здоровье',
  other_info: 'Дополнительная информация',
  sources: 'Источники',
  media: 'Медиа',

  surname: 'Фамилия',
  first_name: 'Имя',
  patronymic: 'Отчество',
  name: 'Фамилия Имя Отчество',
  date: 'Дата',
  day: 'День',
  month: 'Месяц',
  year: 'Год',
  date_raw: {
    editor: 'Дата в свободной форме',
    view: 'Дата (текст)',
  },
  place: 'Место',
  reason: 'Причина',
  cause: 'Причина',
  burial_place: 'Место захоронения',
  person_id: 'Персона',
  relation_type: 'Тип связи',
  marriage: 'Брак',
  divorce: 'Развод',
  education_info: 'Информация',
  title: 'Название',
  job: 'Работа / деятельность',
  service_info: 'Запись о службе',
  war: 'Событие / конфликт',
  achievement: 'Достижение / награда',
  residence_info: 'Место проживания',
  source: 'Источник',
  description: 'Описание',
  link: 'Ссылка',
  other: 'Примечание',
  label: 'Название подпункта',
  text: 'Текст',
};

export const PERSON_SECTION_ORDER = [
  'birth_name',
  'name_changes',
  'birth',
  'death',
  'parents',
  'siblings',
  'spouses',
  'children',
  'education',
  'class_title',
  'religion',
  'nationality',
  'jobs',
  'military_service',
  'war_participation',
  'achievements',
  'residences',
  'hobbies',
  'character',
  'appearance',
  'health',
  'other_info',
  'sources',
  'media',
];

export function getPersonFieldLabel(key, options = {}) {
  const context = options.context || 'view';
  const label = PERSON_FIELD_LABELS[key];

  if (label && typeof label === 'object') {
    return label[context] || label.view || label.editor || key.replaceAll('_', ' ');
  }

  return label || key.replaceAll('_', ' ');
}
